[project]
name = "characterbattletracker"
package-mode=false
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "streamlit>=1.42.2",
]
